#%RAML 1.0 NamedExample

[
  {
    artistId: 1,
    artistName: John,
    genre: Mellow
  },
  {
    artistId: 2,
    artistName: Doe,
    genre: Ballad
  },
  {
    artistId: 2,
    artistName: Lala,
    genre: Alternative
  }
]
